import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const articles=[
{slug:"hvor-kan-ai-skape-verdi-i-en-bedrift",title:"Hvor kan AI skape verdi i en bedrift?",intro:"Start med arbeidsflyten, ikke teknologien. Her er hvordan man finner områdene der AI faktisk kan gjøre en forskjell."},
{slug:"ai-agent-vs-chatbot",title:"AI-agent vs. chatbot",intro:"Forskjellen handler ikke bare om språk. Den handler om hva systemet faktisk kan gjøre."},
{slug:"hvordan-finne-gode-ai-use-cases",title:"Hvordan finne gode AI use cases?",intro:"Gode use cases starter med et konkret problem, en tydelig arbeidsflyt og en målbar effekt."},
{slug:"hvordan-beregne-roi-pa-ai",title:"Hvordan beregne ROI på AI?",intro:"Før man bygger bør man vite hva gevinsten kan være, hva det koster og hvor usikkerheten ligger."}
];
const services={
"ai-opportunity":{title:"AI Opportunity",desc:"Finn hvor AI faktisk kan skape verdi i virksomheten før du begynner å bygge."},
"ai-opportunity-reports":{title:"AI Opportunity Report",desc:"En strukturert vurdering av muligheter, prioritering, forventet effekt og hva dere bør gjøre først."},
"ai-business-workshops":{title:"AI Business Workshop",desc:"En praktisk workshop for ledere og team som vil forstå hvor AI kan brukes i deres egen virksomhet."},
"ai-implementation":{title:"AI Implementation",desc:"Fra prioritert mulighet til en løsning som faktisk blir tatt i bruk."},
"ai-agent-systems":{title:"AI Agent Systems",desc:"AI-systemer som kan utføre, koordinere og følge opp arbeid på tvers av virksomheten."}
};
const mail="mailto:jelassi@smartsvar.no?subject=Uforpliktende%20AI-mulighetsanalyse";
function Meta({path}){useEffect(()=>{let title="Cidea Consulting — Fra muligheter til målbar verdi med AI.",desc="AI rådgivning for bedrifter. Finn, prioriter og implementer AI-muligheter som faktisk kan skape verdi.";const k=path.split("/").filter(Boolean)[0];if(services[k]){title=services[k].title+" | Cidea Consulting";desc=services[k].desc}const a=articles.find(x=>x.slug===path.split("/")[2]);if(a){title=a.title+" | Cidea Consulting";desc=a.intro}if(path==="/blog")title="AI og forretningsutvikling | Cidea Consulting";document.title=title;document.querySelector('meta[name="description"]')?.setAttribute("content",desc);document.querySelector('link[rel="canonical"]')?.setAttribute("href","https://cideaconsulting.com"+path)},[path]);return null}
function Header({lang,setLang}){return <header><a className="logo"href="/">cidea<span>consulting</span></a><nav><a href="/ai-opportunity">AI Opportunity</a><a href="/ai-opportunity-reports">Rapporter</a><a href="/ai-business-workshops">Workshops</a><a href="/ai-agent-systems">Agent Systems</a><a href="/blog">Blogg</a></nav><div className="actions"><button onClick={()=>setLang(lang==="no"?"en":"no")}>{lang==="no"?"EN":"NO"}</button><a className="navCta"href={mail}>{lang==="no"?"Få en vurdering →":"Get an assessment →"}</a></div></header>}
function IntelligenceMap(){return <div className="intelMap"><div className="mapGrid"/><div className="mapLabel">CIDEA / OPPORTUNITY MAP</div><div className="mapCenter">BUSINESS<span>value</span></div><div className="mapNode n1"><b>SALES</b><small>lead research</small></div><div className="mapNode n2"><b>OPERATIONS</b><small>workflow</small></div><div className="mapNode n3"><b>SUPPORT</b><small>knowledge</small></div><div className="mapNode n4"><b>DATA</b><small>analysis</small></div><div className="mapLines"><i/><i/><i/><i/></div><div className="mapFoot">OPPORTUNITY → PRIORITY → IMPACT</div></div>}
function Home({lang}){const en=lang==="en";return <><section className="hero"><div className="heroCopy"><p className="eyebrow">AI CONSULTING / BUSINESS STRATEGY</p><h1>{en?"From opportunity to measurable value with AI.":"Fra muligheter til målbar verdi med AI."}</h1><p className="lead">{en?"We help businesses find, prioritize and implement AI opportunities that save time, reduce costs or create new possibilities.":"Vi hjelper virksomheter med å finne, prioritere og implementere AI-løsninger som sparer tid, reduserer kostnader eller skaper nye muligheter."}</p><div className="actionsHero"><a className="button blue"href={mail}>{en?"Get an AI assessment":"Få en AI-mulighetsanalyse"} ↗</a><a className="textLink"href="#method">Se hvordan vi jobber ↓</a></div><p className="quiet">Ingen kostnad. Ingen forpliktelser.</p></div><IntelligenceMap/></section>
<section className="section thesis"><div className="thesisGrid"><div><p className="eyebrow">THE PRINCIPLE</p><h2>AI er ikke strategien. Verdien er strategien.</h2></div><div><p>Det første spørsmålet er ikke «Hvor kan vi bruke AI?» Det er «Hvor finnes friksjon, kostnad eller uutnyttet kapasitet?»</p><div className="questions"><span>Hvor brukes tid?</span><span>Hvor lekker penger?</span><span>Hvor finnes friksjon?</span><span>Hva kan skaleres?</span></div></div></div></section>
<section className="section opportunity"><div className="intro"><p className="eyebrow blueText">OPPORTUNITY → IMPACT</p><h2>Vi starter med problemet. Ikke teknologien.</h2><p>Gode AI-prosjekter begynner med en konkret arbeidsflyt og en tydelig hypotese om verdi.</p></div><div className="opGrid"><article><span>KARTLEGG</span><h3>Forstå arbeidet</h3><p>Hvor brukes tid? Hvilke prosesser gjentas? Hvor oppstår flaskehalser?</p></article><article><span>IDENTIFISER</span><h3>Finn muligheten</h3><p>Hvilke oppgaver kan automatiseres, assisteres eller forbedres?</p></article><article><span>PRIORITER</span><h3>Velg riktig</h3><p>Vurder effekt, kompleksitet, risiko og hvor raskt verdien kan realiseres.</p></article><article><span>BYGG</span><h3>Gjør det virkelig</h3><p>Test en løsning i praksis før den skaleres videre.</p></article><article><span>MÅL</span><h3>Følg effekten</h3><p>Se om løsningen faktisk sparer tid, reduserer kostnad eller skaper ny kapasitet.</p></article></div></section>
<section className="section usecases"><div className="intro"><p className="eyebrow">WHERE AI CAN HELP</p><h2>Fra små friksjoner til hele arbeidsflyter.</h2></div><div className="useGrid">{["Automatiser rapportering","Reduser administrasjon","La AI håndtere research","Forbedre kundeservice","Bygg interne AI-systemer","Koordiner arbeidsflyter"].map(x=><a href={mail}key={x}><strong>{x}</strong><em>Vurder muligheten →</em></a>)}</div></section>
<section className="section method" id="method"><div className="intro"><p className="eyebrow">HOW WE WORK</p><h2>Fra hypotese til løsning.</h2></div><div className="methodList"><div><span>KARTLEGG</span><h3>Kartlegg</h3><p>Vi forstår virksomheten, prosessene og målene.</p></div><div><span>IDENTIFISER</span><h3>Identifiser</h3><p>Vi finner konkrete AI-muligheter med en tydelig business case.</p></div><div><span>PRIORITER</span><h3>Prioriter</h3><p>Vi velger hva som er verdt å teste først.</p></div><div><span>BYGG</span><h3>Bygg</h3><p>Vi utvikler, integrerer og setter løsningen i arbeid.</p></div><div><span>MÅL</span><h3>Mål</h3><p>Vi følger effekten og forbedrer løsningen over tid.</p></div></div></section>
<section className="section agent"><div className="agentCopy"><p className="eyebrow blueText">AI AGENT SYSTEMS</p><h2>Ikke bare en chatbot. Et system som kan gjøre arbeid.</h2><p>Vi kan bygge AI-systemer som kobler kunnskap, verktøy og arbeidsflyter slik at AI kan utføre og koordinere oppgaver på tvers av virksomheten.</p><a className="textLink"href="/ai-agent-systems">Utforsk Agent Systems →</a></div><div className="agentStack"><div>BUSINESS MANAGER</div><i>↓</i><div><span>SALES</span><span>MARKETING</span><span>SUPPORT</span></div><i>↓</i><div className="execution">EXECUTION / TOOLS / DATA</div></div></section>
<section className="section report"><div><p className="eyebrow">START SMALL</p><h2>Finn ut hvor AI faktisk kan skape verdi.</h2><p>Vi gjør en uforpliktende vurdering av virksomheten din og peker på konkrete muligheter. Ingen kostnad. Ingen forpliktelser.</p><a className="button blue"href={mail}>Få en AI-mulighetsanalyse →</a></div><div className="reportCard"><span>CIDEA / AI OPPORTUNITY</span><strong>OPPORTUNITY<br/>MAP</strong><small>VALUE / COMPLEXITY / PRIORITY</small></div></section>
<section className="section journal"><div className="intro"><p className="eyebrow">INSIGHT</p><h2>AI forklart gjennom forretningsproblemer.</h2></div><div className="articleGrid">{articles.slice(0,3).map(a=><a href={"/blog/"+a.slug}key={a.slug}><span>ARTICLE</span><h3>{a.title}</h3><p>{a.intro}</p><b>Les artikkelen →</b></a>)}</div></section>
<section className="final"><p className="eyebrow">THE NEXT STEP</p><h2>Start med spørsmålet som betyr noe.</h2><p>Hvor kan AI skape mest verdi i akkurat deres virksomhet?</p><a className="button blue"href={mail}>Få en AI-mulighetsanalyse →</a></section></>}
undefined
function Blog({article}){return <section className="page">{article?<><p className="eyebrow">INSIGHT</p><h1>{article.title}</h1><p className="pageLead">{article.intro}</p><div className="articleBody"><p>{article.intro} Den beste måten å vurdere dette på er å koble teknologien til en konkret arbeidsflyt, forventet effekt og hva som må til for å ta løsningen i bruk.</p></div><a className="textLink"href="/blog">← Alle artikler</a></>:<><p className="eyebrow">INSIGHT</p><h1>AI og forretningsutvikling.</h1><p className="pageLead">Praktiske svar om AI, automatisering, use cases og verdiskaping.</p><div className="articleList">{articles.map((a,i)=><a href={"/blog/"+a.slug}key={a.slug}><span>ARTICLE</span><h2>{a.title}</h2><p>{a.intro}</p><b>Les artikkelen →</b></a>)}</div></>}</section>}
function App(){const[lang,setLang]=useState("no");const path=location.pathname.replace(/\/$/,"")||"/";<Meta path={path}/>;const key=path.split("/").filter(Boolean)[0];const article=articles.find(a=>a.slug===path.split("/")[2]);const content=path==="/"?<Home lang={lang}/>:path==="/blog"||article?<Blog article={article}/>:services[key]?<Service data={services[key]}/>:<Home lang={lang}/>;return <div className="site"><Header lang={lang}setLang={setLang}/><main>{content}</main><footer><a className="logo"href="/">cidea<span>consulting</span></a><span>AI consulting · Oslo / Norge</span><a href={mail}>Kontakt →</a></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);